### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by yongfei25** [twitter/torch-ipc#11]
Hello,

I'm using a AWS instance **without** Nvidia device, even though the machine image comes with cuda driver installed. I did not use ipc with cuda.

By just running `allreduce.sh` example (cuda not enabled) and got:

```
/home/ubuntu/torch/install/share/lua/5.1/ipc/Tree.lua:36: cuda runtime error (38) : 
no CUDA-capable device is detected at /home/ubuntu/torch-ipc/src/cliser.c:235
```

**Comment by zakattacktwitter** [comment]
Whoops, this should fix it:

https://github.com/twitter/torch-ipc/pull/12

Once the CI completes I will merge it. Thanks.

**Comment by yongfei25** [comment]
Thanks!
