### ISSUE TITLE
"CUDA IPC not possible between GPUs" & "CUDA IPC enabled between GPUs"

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-ipc#15]
Hi, I apply the same training parameters on AWS Ubuntu instance and local GPU machine. It is correct on the AWS Ubuntu instance but I got strange results on the local GPU machine. Do you have any idea? Here are 1 epoch results of MNIST dataset.

Thank you.

Chien-Lin

----- on the AWS Ubuntu instance (GPU, GRID K520) -----
**1gpu,              global correct: 98.5%,          total time: 135.9 sec
2gpu,              global correct: 98.1%,          total time: 112.9 sec
4gpu,              global correct: 97.5%,          total time:   89.3 sec**

----- on the local GPU CentOS machine (GPU, Tesla K80) -----
**1gpu,              global correct: 97.2%,          total time: 135.7 sec**
**2gpu,              global correct: 10.4%,          total time: ~20790 sec**
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
**4gpu,              global correct: 10.2%,          total time: ~10410 sec**
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU2
INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
INFO: torch-ipc: CUDA IPC enabled between GPU3 and GPU2
INFO: torch-ipc: CUDA IPC enabled between GPU2 and GPU3

**Comment by zakattacktwitter** [comment]
Hi,

Can you trying running the allgpu-allreduce.lua script in benchmarks? Try with the --verify flag to make sure your GPU to GPU communication is working properly.

Thanks,
Zak

**Comment by chienlinhuang1116** [comment]
Thank you Zak. Yes, I try it and get the following information. Do you have any idea?

Thanks,
Chien-Lin

-bash-4.1$ th ./allgpu-allreduce.lua -v
Found 8 GPUs, forking children...
INFO: torch-ipc: CUDA IPC not possible between GPU2 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU2
INFO: torch-ipc: CUDA IPC not possible between GPU5 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU5
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU6
INFO: torch-ipc: CUDA IPC not possible between GPU6 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU4
INFO: torch-ipc: CUDA IPC not possible between GPU4 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
INFO: torch-ipc: CUDA IPC not possible between GPU3 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU3
INFO: torch-ipc: CUDA IPC not possible between GPU7 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU7
INFO: torch-ipc: CUDA IPC enabled between GPU2 and GPU3
INFO: torch-ipc: CUDA IPC enabled between GPU3 and GPU2
INFO: torch-ipc: CUDA IPC enabled between GPU5 and GPU4
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU5
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU7
INFO: torch-ipc: CUDA IPC enabled between GPU7 and GPU6
INFO: torch-ipc: CUDA IPC enabled between GPU4 and GPU6
INFO: torch-ipc: CUDA IPC enabled between GPU6 and GPU4
/home/chienh/torch/install/bin/luajit: ./allgpu-allreduce.lua:63: err too high: inf
stack traceback:
        [C]: in function 'assert'
        ./allgpu-allreduce.lua:63: in main chunk
        [C]: in function 'dofile'
        ...ienh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405800

**Comment by zakattacktwitter** [comment]
Closing, as #17 has all the information we need to figure out this bug.
