### ISSUE TITLE
How can I disable "CUDA IPC enabled between GPUs"?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-ipc#16]
Hi, I think torch-ipc will automatically enable between GPUs. How can I disable this function?

Thank you.

Chien-Lin

**Comment by chienlinhuang1116** [comment]
Hi I know how to disable this function by modifying the file of "cliser.c" 

if (device != remote_device) {
         int can;
         THCudaCheck(cudaDeviceCanAccessPeer(&can, device, remote_device));
         /*if (can) {
            cudaError_t err = cudaDeviceEnablePeerAccess(remote_device, 0);
            if (err == cudaSuccess || err == cudaErrorPeerAccessAlreadyEnabled) {
               if (err == cudaErrorPeerAccessAlreadyEnabled) cudaGetLastError();
               fprintf(stderr, "INFO: torch-ipc: CUDA IPC enabled between GPU%d and GPU%d\n", device, remote_device);
               return 1;
            } else {
               fprintf(stderr, "WARN: torch-ipc: CUDA IPC disabled between GPU%d and GPU%d: %s\n", device, remote_device, cudaGetErrorString(err));
            }
         } else {
            fprintf(stderr, "INFO: torch-ipc: CUDA IPC not possible between GPU%d and GPU%d\n", device, remote_device);
         }*/
      }

and then running "luarocks make ipc-scm-1.rockspec". Thank you.

Chien-Lin

**Comment by zakattacktwitter** [comment]
Closing, as #17 has all the information we need to figure out this bug.
