### ISSUE TITLE
What is the correct setting of GPU cards?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-ipc#17]
Hi, I have a machine with 8 GPU cards. The information of their topo matrix is shown as follows. Is this a correct setting to test Torch-IPC, or Do you have any comment?

Thanks,
Chien-Lin

```
-bash-4.1$ nvidia-smi topo --matrix
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity
GPU0     X      PIX     SOC     SOC     SOC     SOC     SOC     SOC     0-7,16-23
GPU1    PIX      X      SOC     SOC     SOC     SOC     SOC     SOC     0-7,16-23
GPU2    SOC     SOC      X      PIX     PHB     PHB     PHB     PHB     8-15,24-31
GPU3    SOC     SOC     PIX      X      PHB     PHB     PHB     PHB     8-15,24-31
GPU4    SOC     SOC     PHB     PHB      X      PIX     PXB     PXB     8-15,24-31
GPU5    SOC     SOC     PHB     PHB     PIX      X      PXB     PXB     8-15,24-31
GPU6    SOC     SOC     PHB     PHB     PXB     PXB      X      PIX     8-15,24-31
GPU7    SOC     SOC     PHB     PHB     PXB     PXB     PIX      X      8-15,24-31

Legend:

  X   = Self
  SOC = Path traverses a socket-level link (e.g. QPI)
  PHB = Path traverses a PCIe host bridge
  PXB = Path traverses multiple PCIe internal switches
  PIX = Path traverses a PCIe internal switch

```

In addition, the following results are shown in the case of 2GPUs:
```
-bash-4.1$ ./mnist-cuda45-PIX.sh
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
**Output: incorrect results (long time & low accuracy)**

-bash-4.1$ ./mnist-cuda46-PXB.sh
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
**Output: incorrect results (long time & low accuracy)**

-bash-4.1$ ./mnist-cuda43-PHB.sh
INFO: torch-ipc: CUDA IPC enabled between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC enabled between GPU0 and GPU1
**Output: 1-epoch, global correct: 97.9%, total time: 108.4 sec**

-bash-4.1$ ./mnist-cuda43.sh
INFO: torch-ipc: CUDA IPC not possible between GPU1 and GPU0
INFO: torch-ipc: CUDA IPC not possible between GPU0 and GPU1
**Output: 1-epoch, global correct: 98.1%, total time: 113.5 sec**
```

**Comment by zakattacktwitter** [comment]
Hi,

Sorry you are having so much trouble. Can you run the CUDA SDK sample for simpleP2P? I have a feeling there is something wrong with your machine's setup.

There's a security feature called ACS that needs to be disabled in order for the GPUs to be able to talk to each other correctly.

First find out your PCI switch addresses:

```
lspci | grep -i plx
```

You should see something like this as output:

```
02:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
03:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
03:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
06:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
07:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
07:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
```

Then look to see if ACS is enabled on each one:

```
lspci -s 02:00.0 -vvvv|grep -i acs
```

If you see results like the following, then ACS is enabled, you need to turn it off.

```
UESta: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UEMsk: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UESvrt: DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
```

See this post from SuperMicro for more information http://www.supermicro.com/support/faqs/faq.cfm?faq=20732

Hope this helps!

**Comment by chienlinhuang1116** [comment]
Hi Zak. 

Here is the output:

-bash-4.1$ lspci | grep -i plx
02:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
03:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
03:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
81:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
82:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
82:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
85:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
86:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
86:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
87:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
88:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
88:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8b:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8c:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8c:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca) 

Then, I check if ACS is enabled on each one:

-bash-4.1$ lspci -s 02:00.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 03:08.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 03:10.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 81:00.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 82:08.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 82:10.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 85:00.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 86:08.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 86:10.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 87:00.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 88:08.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 88:10.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 8b:00.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 8c:08.0 -vvvv|grep -i acs
-bash-4.1$ lspci -s 8c:10.0 -vvvv|grep -i acs

Do you have any idea?

Thank you very much & sorry for the hassle.

Chien-Lin

**Comment by zakattacktwitter** [comment]
Did you try the simpleP2P example that comes with the CUDA SDK?

**Comment by chienlinhuang1116** [comment]
Hi Zak, 

I can get the same output like yours if using **sudo**. Base on information [,](http://www.supermicro.com/support/faqs/faq.cfm?faq=20732), can I run "setpci -s 02:00.0 f2a.w=0000" to disable ASC because I don't see "ACSCtl: SrcValid-" or "ACSCtl: SrcValid+" in the following output ?

Thanks,
Chien-Lin

```
-bash-4.1$ sudo lspci -s 02:00.0 -vvvv|grep -i acs
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
```
