### ISSUE TITLE
What is the correct performance of multiple GPUs?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-ipc#19]
Hi,

I tested MNIST dataset with multiple GPUs (Tesla K80) and get the time complexity with different settings. I have some questions based on the following results:
(1) Are these results expected? 'disable ACS & enable IPC' is about 10% relative faster than 'enable ACS & disable IPC'.
(2) Microsoft reported one-bit SGD methods and had 7 times faster between using single GPU and 8 GPUs ([cntk toolkit](https://blogs.technet.microsoft.com/inside_microsoft_research/2015/12/07/microsoft-computational-network-toolkit-offers-most-efficient-distributed-deep-learning-computational-performance/)). I can had about 2 times faster between using single GPU (656.3sec) and 8 GPUs (357.0sec). Is my setting or result correct?
(3) What is the expected performance of multiple GPUs using torch-ipc and torch-distlearn?

Thank you very much,
Chien-Lin

**1-epoch**
![image](https://cloud.githubusercontent.com/assets/16109566/13640969/a2b6ca3e-e5cb-11e5-8a93-5f7bc4f781da.png)

**5-epoch**
![image](https://cloud.githubusercontent.com/assets/16109566/13641022/db48b3f8-e5cb-11e5-9682-96ef319331fa.png)

**Comment by zakattacktwitter** [comment]
Hi,

Glad you got your GPUs working. The MNIST problem is tiny and not really
big enough to demonstrate big speed ups using distributed learning. You
might consider trying a model with a much more complicated/expensive
gradient as well as a exceptionally larger data set size.

I'd include a model of that size as an example if one existed in the public
domain.

Hope this helps,
Zak

**Comment by chienlinhuang1116** [comment]
Thank you Zak.
