### ISSUE TITLE
Is there any issue when we use the large data input?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-ipc#23]
Hi, we saved our data to torch senor format 'train.t7' and loaded it using torch-dataset.

local trainingDataset = Dataset('train.t7', {partition = 1, partitions = 1})

If the size of 'train.t7' is 500GB or more, is there any limitation in the memory when using torch-dataset? Is there any issue when we define 'batchSize' or use 'torch-ipc'?

Thank you.

**Comment by zakattacktwitter** [comment]
There are a couple limits.

1) The size of your computer's memory.
2) The number of open file handles you can have. This is particularly troublesome on OSX where the limit is low. Torch's require system opens tons of files. If you spawn 100s of threads (via ipc.map or a large batch size) then you could run out of file handles.

**Comment by chienlinhuang1116** [comment]
Thank you :)
